name: second_pulser
description: "Feel the seconds pulse by on your wrist"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  wear_plus: ^1.2.1
  wearable_rotary: ^2.0.2
  flutter_foreground_service: ^0.4.1
  vibration: ^1.8.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
