package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new de.julianassmann.flutter_background.FlutterBackgroundPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin flutter_background, de.julianassmann.flutter_background.FlutterBackgroundPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new dk.cachet.flutter_foreground_service.FlutterForegroundServicePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin flutter_foreground_service, dk.cachet.flutter_foreground_service.FlutterForegroundServicePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new dev.rexios.wear_plus.WearPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin wear_plus, dev.rexios.wear_plus.WearPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.samsung.wearable_rotary.WearableRotaryPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin wearable_rotary, com.samsung.wearable_rotary.WearableRotaryPlugin", e);
    }
  }
}
